### ISSUE TITLE
Support for YAML repeated nodes in Liquid

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-plugin-datastruct#11]
*In relation to https://github.com/ituob/service-publications-docs/issues/1*

I'm getting `Liquid error: internal` on YAML files that contain [repeated nodes](https://yaml.org/spec/1.2/spec.html#id2760395).

Example:
````
---
groups:
  amateur: &general
    regex: O[F-J][:digit:][0-9A-Z]{3}[:upper:]{1}

  experimental: *general
````
being `&general` a node object, and `*general` the reference to that object.

**Comment by ronaldtse** [comment]
I think the problem here is the YAML parser not recognising repeated nodes? Or is the liquid filter not supporting that?

**Comment by w00lf** [comment]
> ituob/service-publications-docs#1

Hi there @manuel489 can you please provide yaml2text, macro itself? It does not look like yaml error, it seems that you referencing not existing attribute

**Comment by manuel489** [comment]
Hi @w00lf, sure.
For example, taking the following yaml file:

````
#Finland
#Amateur stations and
#experimental stations:
#OF, OG, OH, OI or OJ followed by a digit and a group of not more than 4 characters, the last of which shall be a letter

groups:
  amateur: &general
    regex: O[F-J][:digit:][0-9A-Z]{3}[:upper:]{1}

  experimental: *general
````

a simple yaml2text macro would be:

````
[yaml2text,yaml_files/finland.yaml,data]
----
=== Findland

Amateur stations and experimental stations:: {{ data.groups.amateur.regex }}
----
````

This shows nothing in output. 
But if the yaml2text was nested into another yaml2text block, I get `Liquid error: internal`.
